version: "3.9"

services:
  # Container definition for the devcontainer
  devcontainer:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces/marty_mcfly/

networks:
  default:
    name: marty_mcfly-network
